project_name: civo
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
      - solaris
      - openbsd
      - freebsd
    goarch:
      - 386
      - amd64
      - arm
    ignore:
      - goos: darwin
        goarch: 386
      - goos: solaris
        goarch: 386
      - goos: openbsd
        goarch: arm
    ldflags:
      - -s -w -X github.com/civo/cli/cmd.VersionCli={{.Version}} -X github.com/civo/cli/cmd.CommitCli={{.Commit}} -X github.com/civo/cli/cmd.DateCli={{.Date}}
checksum:
  name_template: '{{ .ProjectName }}-{{ .Version }}-checksums.sha256'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - Merge pull request
      - Merge branch
archives:
  - name_template: '{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}'
    format_overrides:
      - goos: windows
        format: zip