project_name: civo
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
      - solaris
      - openbsd
      - freebsd
    goarch:
      - 386
      - amd64
      - arm
    ignore:
      - goos: darwin
        goarch: 386
      - goos: solaris
        goarch: 386
      - goos: openbsd
        goarch: arm
    ldflags:
      - -s -w -X github.com/civo/cli/cmd.VersionCli={{.Version}} -X github.com/civo/cli/cmd.CommitCli={{.Commit}} -X github.com/civo/cli/cmd.DateCli={{.Date}}
checksum:
  name_template: "{{ .ProjectName }}-{{ .Version }}-checksums.sha256"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - Merge pull request
      - Merge branch
archives:
  - name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
brews:
  - name: civo
    github:
      owner: civo
      name: homebrew-tools
    commit_author:
      name: civobot
      email: hello@civo.com
    folder: formula
    homepage: "https://github.com/civo/cli"
    description: "CLI for managing Civo resources."
dockers:
  -
    goos: linux
    goarch: amd64
    binaries:
    - civo
    image_templates:
    - "civo/cli:latest"
    - "civo/cli:{{ .Tag }}"
    dockerfile: docker/Dockerfile
snapcrafts:
  - name_template: '{{ .ProjectName }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    summary: Tool to handler all Civo cloud resource
    description: |
      Civo CLI is a tool to handler all resource inside the Civo cloud, from the console.
    grade: stable
    confinement: strict
    publish: true
  - apps:
      civo:    
        plugs: ["network", "network-bind"]