project_name: civo
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
      - solaris
      - openbsd
      - freebsd
    goarch:
      - 386
      - amd64
      - arm
    ignore:
      - goos: darwin
        goarch: 386
      - goos: solaris
        goarch: 386
      - goos: openbsd
        goarch: arm
checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - Merge pull request
      - Merge branch
archives:
  - name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    format_overrides:
      - goos: windows
        format: zip